import { type InspectOptions } from './types.js'

export const DEFAULT_OPTIONS: InspectOptions = {
  noanimate: false,
  animRate: 1,
  easing: undefined,
  quotes: 'single',
  showTypes: true,
  showPreview: true,
  previewDepth: 1,
  previewEntries: 3,
  flashOnUpdate: true,
  showLength: true,
  showTools: true,
  stringCollapse: 0,
  theme: 'inspect',
  borderless: false,
  customComponents: {},
  expandAll: false,
  expandLevel: 1,
  expandPaths: [],
  embedMedia: false,
  elementView: 'simple',
  renderIf: true,
  parseJson: false,
  onCopy: undefined,
  canCopy: undefined,
  onLog: undefined,
  onCollapseChange: undefined,
  stores: 'full',
  search: false,
  searchMode: 'or',
  highlightMatches: true,
  heading: false,
  hotkeys: true,
  disableKeynav: false,
  typeToFocus: true,
} as const

export const OPTIONS_KEYS = Object.keys(DEFAULT_OPTIONS) as (keyof InspectOptions)[]
