import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { transform } from 'typedoc-better-json'

// console.log(path)

const dir = fileURLToPath(new URL('..', import.meta.url))

async function Example() {
  // read the JSON file generated by typedoc
  const fileContent = await readFile(`${dir}/src/doclib/typedoc/docs.json`, 'utf8')

  // parse it
  const fileData = JSON.parse(fileContent)

  // transform it
  const transformedData = transform(fileData)

  // save it in file
  await writeFile(
    `${dir}/src/doclib/typedoc/transformed-doc.json`,
    JSON.stringify(transformedData, null, 2)
  )
}

await Example()

// const pkg = JSON.parse(fs.readFileSync(`${dir}/package.json`, 'utf-8'))

// console.log(dir)
