name: 'Pull request'
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      
      - name: 'Install pnpm'
        uses: pnpm/action-setup@v4
        with:
          version: '10.33.2'  # or whatever version you're using locally
      
      - name: 'Install Node'
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'pnpm'  # Cache pnpm dependencies
      
      - name: 'Install Deps'
        run: pnpm install --frozen-lockfile
      
      - name: 'Build all'
        run: pnpm --recursive --filter '!docs' build && pnpm --filter docs build
      
      - name: 'Test'
        run: pnpm --filter './packages/*' test